### ISSUE TITLE
Rating value is calculated incorrectly 

### ISSUE THREAD

**Issue by vitidev** [a914-gowtham/compose-ratingbar#11]
The rating value computation function is very sensitive to padding. 
When padding is 3.dp - everything is fine 

But if the padding is large, then
1) It register misclicks between stars
2) the calculated value exceeds the maximum

for example

       var rating: Float by rememberSaveable { mutableStateOf(0f) }

       Column() {
           Text(text = rating.toString())
       RatingBar(
           value = rating,
           size = 20.dp,
           padding = 30.dp,
           numStars = 3,
           ratingBarStyle = RatingBarStyle.HighLighted,
           onRatingChanged = {
               rating=it
           })
       }

max value is 9

**Comment by a914-gowtham** [comment]
Currently, rating value is calculated from the full width of the ratingbar. I will check the workaround and taking this issue as a low priority.

**Comment by tidimito** [comment]
The calculating algorithm is unuseful. Please increase the priority of this task. Thanks.

**Comment by a914-gowtham** [comment]
@tidimito  thanks for creating this issue. my bad it should have been fixed earlier.  fixed in [1.3.0](https://github.com/a914-gowtham/compose-ratingbar/releases/tag/1.3.0) now
