### ISSUE TITLE
the ability to hide inactive stars 

### ISSUE THREAD

**Issue by vitidev** [a914-gowtham/compose-ratingbar#13]
Please add a parameter `showInactiveStars: Boolean = true` to hide inactive stars.
In indicator mode, they are not always needed, but they take resources

**Comment by a914-gowtham** [comment]
@vitidev  Thanks for creating valuable issues. It has been added in [#4a1a671](https://github.com/a914-gowtham/compose-ratingbar/commit/22f4613e8ba83d21286c9a6d6e87d2cebadb924a) commit. i will check #12 #11 issues and make a release with the fix ASAP

**Comment by a914-gowtham** [comment]
You can use the v1.1.1 of the library. it has been added as param `hideInactiveStars: Boolean = false`.
