### ISSUE TITLE
Customisable star shape / icon

### ISSUE THREAD

**Issue by galonga** [a914-gowtham/compose-ratingbar#23]
Hey,
I would love to have customizable star shapes or better vector assets. This would add some more flexibility to the layout and could be part of the `RatingBarConfig`.

**Comment by a914-gowtham** [comment]
@galonga  I will add it to my road map. I'm not sure about eta though. I found this nice library https://github.com/SmartToolFactory/Compose-RatingBar try this one it might be useful.

**Comment by a914-gowtham** [comment]
Hi @galonga,  custom icon feature is added in v1.3.1. check the updated readme for the detail
