### ISSUE TITLE
Padding should be only between stars and other improvements

### ISSUE THREAD

**Issue by FXeio** [a914-gowtham/compose-ratingbar#3]
I think that the `padding` parameter should be used only between stars, not all around. To pass a padding for the container a modifier provided by the user should be used instead

We should also move the `onRatingChanged` lambda parameter at the end, so that it can be passed as [trailing lambda](https://kotlinlang.org/docs/lambdas.html#passing-trailing-lambdas)

**Comment by a914-gowtham** [comment]
Added in `   implementation 'com.github.a914-gowtham:compose-ratingbar:1.0.3'
`
