### ISSUE TITLE
Want to disable rating change when a vertical scroll is performed

### ISSUE THREAD

**Issue by thepraveshsinghh** [a914-gowtham/compose-ratingbar#36]
Hey this rating bar is amazing but I am facing an issue with it.
PROBLEM -> I have added the rating bar to a column with vertical scroll, I want that if the user scrolls vertically even on the rating bar nothing should happen to the rating and the column should scroll normally. But right now as soon as we touch the rating bar the rating changes.

Is there any way to achieve this?

**Comment by a914-gowtham** [comment]
@thepraveshsinghh hi, thanks for figuring out the issue i have added the fix v1.3.5

**Comment by thepraveshsinghh** [comment]
Thanks brother 🤝 for resolving this so quick.

**Comment by a914-gowtham** [comment]
getting error in jitpack will update

**Comment by a914-gowtham** [comment]
added in [v1.3.6](https://github.com/a914-gowtham/compose-ratingbar/releases)
