### ISSUE TITLE
Some way to know when the user is done selecting a rating

### ISSUE THREAD

**Issue by FXeio** [a914-gowtham/compose-ratingbar#5]
In the future one might need to know when the swipe motion is completed and the finger is lifted from the screen (e.g. to open a review screen)

**Comment by a914-gowtham** [comment]
Yes, you are right. I need to check the possible ways to implement it.

**Comment by a914-gowtham** [comment]
I have made some changes to the onRatingChanged function. it will be called once ratingbar is clicked or drag is released as same as default behaviour of android ratingbar's setOnRatingBarChangeListener interface.

```gradle
   implementation 'com.github.a914-gowtham:compose-ratingbar:1.0.4'
```
```kotlin
var rating: Float by rememberSaveable { mutableStateOf(initialRating) }

        RatingBar(value = rating,onRatingChanged = {
            rating=it
            //Navigation code
        })
   ```
