### ISSUE TITLE
RatingBar is not compatible with compose version 1.0.0-beta07

### ISSUE THREAD

**Issue by anomaly2798** [a914-gowtham/compose-ratingbar#6]

**Comment by Vivecstel** [comment]
Can we have an estimation for this ?

**Comment by a914-gowtham** [comment]
@Vivecstel Within a hour

**Comment by Vivecstel** [comment]
Thanks a lot :)

**Comment by a914-gowtham** [comment]
@Vivecstel Can you try this
`	        implementation 'com.github.a914-gowtham:compose-ratingbar:1.0.5'
`

**Comment by Vivecstel** [comment]
@a914-gowtham Just run in :) this version is ok. thanks :)
