### ISSUE TITLE
How to make a transparent background? 

### ISSUE THREAD

**Issue by vitidev** [a914-gowtham/compose-ratingbar#9]
Surface in RatingBar is not transparent and I don't understand how to make it transparent. It looks like need to make an additional backgroundColor parameter.

**Comment by a914-gowtham** [comment]
@vitidev  my bad. I should have removed the surface in the ratingbar. now, It is removed and will be updated by tonight.

**Comment by Psijic** [comment]
I use ComposeStars for it

**Comment by vitidev** [comment]
>I use ComposeStars for it

What is 'ComposeStars'?

**Comment by Psijic** [comment]
> What is 'ComposeStars'?

A subcomponent of RatingBar.

**Comment by a914-gowtham** [comment]
@vitidev  It has been fixed in #4a1a671 commit. I will check #12 #11 issues and make a release with the fix ASAP. Thanks

**Comment by a914-gowtham** [comment]
Surface of Ratingbar composable is removed in the latest release, you can use v1.1.1. thanks for making this library usable.
